### ISSUE TITLE
v0.2.15 breaks sparkleformation

### ISSUE THREAD

**Issue by universam1** [spox/bogo#7]
@chrisroberts https://github.com/spox/bogo/releases/tag/v0.2.15 breaks sparkleformation run:

```
se `bundle info [gemname]` to see where a bundled gem is installed.
Attempting to run deploy
[ERROR]: Failed to create remote API connection. Please validate configuration!
[ERROR]: Connection failure reason - Miasma::Error - Failed to load requested API type :Orchestration (Reason: NoMethodError - undefined method `lock' for nil:NilClass)
[ERROR]: Failed to load requested API type :Orchestration (Reason: NoMethodError - undefined method `lock' for nil:NilClass)
```

ref: https://github.com/sparkleformation/sparkle_formation/issues/273

**Comment by horori** [comment]
I see the problem with `Miasma::Types::Api` https://github.com/miasma-rb/miasma/blob/develop/lib/miasma/types/api.rb#L28

I was able to reproduce the problem with this minimum code.

```ruby
module TestUtils
  Lazy = Bogo::Lazy
end

class Test
  include TestUtils::Lazy
  def initialize(creds)
    load_data(creds)
  end
end

Test.new({foo: 'bar'}) # NoMethodError: undefined method `lock' for nil:NilClass from /usr/local/lib/ruby/2.6.0/monitor.rb:192:in `mon_enter'
```

I wonder if `Bogo::Lazy` got an issue with Thread handling.
https://github.com/spox/bogo/blob/v0.2.15/lib/bogo/lazy.rb#L59

**Comment by mikelorant** [comment]
This was broken in this commit: https://github.com/spox/bogo/commit/96413e820aa7e5387bcb66d1eb9ff224ab7d04b2

What is quite interesting is the addition of `monitor` gem which is not in the `gemspec`. This gem has also been yanked. I think this explains why there may be no method for `synchronize`.
